version: "4.48"

services:

  web:
    build: .
    container_name: jhon_app
    ports:
      - "8000:8000"
    volumes:
      - .:/Curso_CICD/api_desplegar
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
