version: "3.8"
services:
  app:
    build: .
    container_name: miapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  tests:
    build: .
    container_name: test_runner
    command: pytest -v
    depends_on:
      - app
