version: "4.48.0"

services:

  web:
    build: .
    container_name: samuelapp
    ports:
      - "8000:8000"
    volumes:
      - .:/Curso_CICD/API
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
